apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.metadata.name }}
  name: {{ .Values.metadata.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.name }}
    spec:
      containers:
      - image: kareemelkasaby/itimans{{ .Values.metadata.name }}:7
        name: {{ .Values.metadata.name }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}