apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.metadata.name }}
  name: {{ .Values.metadata.name }}
spec:
  ports:
  - name: bakehouseport
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: {{ .Values.metadata.name }}
  type: NodePort
status:
  loadBalancer: {}
